services:
  - type: web
    name: atelier-upwork-scraper
    runtime: node
    buildCommand: ./render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/puppeteer/chrome/linux-148.0.7778.97/chrome-linux64/chrome
